theme = "dark_flat"

padding = [0, 5]
line-height = 1.2

option-as-alt = "left"
hide-mouse-cursor-when-typing = true

[cursor]
shape = "underline"
blinking = false

[bell]
audio = true

[editor]
program = "nvim"

[effects]
trail-cursor = false

[window]
mode = "Maximized"
opacity = 0.85
blur = "macos-glass-clear"
decorations = "Buttonless"
macos-use-shadow = true

[renderer]
performance = "High"
level = 1
target-fps = 120

[fonts]
size = 14
use-drawable-chars = true
family = "LigaSFMono Nerd Font"

[scroll]
multiplier = 3.0
divider = 1.0

[navigation]
mode = "Tab"
clickable = true
hide-if-single = true
use-current-path = true
