# Which is equivalent to
format = """
$username\
$hostname\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$swift\
$terraform\
$vlang\
$vagrant\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$line_break\
$jobs\
$character"""

right_format = """$cmd_duration"""

# Disable the blank line at the start of the prompt
add_newline = false

[cmd_duration]
min_time = 0
show_milliseconds = true
format="[$duration]($style)"
style = "bold cyan"

[character] 
success_symbol = "[ ](fg:#3dd177)"     
error_symbol = "[ ](fg:#ff6633)"

[directory]
style = "fg:#00b0ff"

[git_branch]
always_show_remote = true
style = "fg:#3dd177"

[git_metrics]
disabled = false
