# set default editor
editor /usr/local/bin/lvim


# shell integration
shell_integration no-cursor

# fonts 
font_family      Liga SFMono Nerd Font Semibold
bold_font        Liga SFMono Nerd Font Bold
italic_font      Liga SFMono Nerd Font Semibold Italic
bold_italic_font Liga SFMono Nerd Font Bold Italic
font_size 13.0

# adjust_line_height, adjust_column_width
adjust_line_height  1
adjust_column_width 0

# ligatures
disable_ligatures never

# cursor customization
cursor #ee2c68
cursor_text_color #000000
# shape: block, beam, underline
cursor_shape underline
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
#: Defines the thickness of the underline cursor (in pts)
cursor_blink_interval 0

# scroll
scrollback_lines 2000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollback_pager_history_size 0
touch_scroll_multiplier 1.0

# url
url_color #005bbb
url_style curly
open_url_with default
url_prefixes http https file ftp gemini irc gopher mailto news git
detect_urls yes

copy_on_select no
strip_trailing_spaces smart
select_by_word_characters @-./_~?&=%+#
click_interval -1.0
focus_follows_mouse yes
repaint_delay 10
input_delay 3
sync_to_monitor no

# bell
enable_audio_bell yes
visual_bell_duration 0.0
window_alert_on_bell yes

# window size
remember_window_size no
initial_window_width  80c
initial_window_height 25c

# tab
tab_bar_style powerline
active_tab_foreground  #fff
active_tab_background  #000
tab_title_template "{index}: {title}"

enabled_layouts *

window_margin_width 0
window_padding_width 0 5

placement_strategy center

inactive_text_alpha 1.0

hide_window_decorations titlebar-only

resize_draw_strategy static

# color scheme 
foreground #eceef0
background #18191a
background_opacity 0.85
selection_foreground #f0f0f0
selection_background #25b1f5

# black
color0 #000000
color8 #b0bec4

#: red
color1 #ee2c68
color9 #ee3c75

#: green
color2  #3dd177
color10 #82f4a2

#: yellow
color3  #ffc900
color11 #ffe47e

#: blue
color4  #00b0ff
color12 #80d7fe

#: magenta
color5  #ff3f80
color13 #ff80ab

#: cyan
color6  #64fcda
color14 #a7fdeb

#: white
color7  #fefefe
color15 #fefefe

term xterm-kitty

# macos specific setup
macos_window_resizable yes
macos_show_window_title_in menubar
macos_option_as_alt left

# key mapping
map cmd+shift+enter launch --cwd=current
map cmd+shift+t new_tab_with_cwd
map cmd+shift+n new_os_window_with_cwd
