update:
  days: 7
gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - "#4b5261"
  branchColors:
    "docs": blue
    "fix": red
    "feat": green
notARepository: "skip"
git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
os:
  edit: "nvim"
customCommands:
  - key: "G"
    command: |
      git fetch -p && for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}'); do git branch -D $branch; done
    context: "localBranches"
    description: "Prune local branches no longer on its remote."
    loadingText: "Pruning..."
  - key: "U"
    command: "git submodule update --init --recursive"
    context: "global"
    description: "Update submodules"
    loadingText: "Updating Submodules..."
