[misc]
assume_yes = true
pre_sudo = true
sudo_command = "sudo"
disable = [
  "system",
  "node",
  "yarn",
  "pnpm",
  "pip3",
  "containers",
  "gem",
  "ruby_gems",
]
no_retry = true
display_time = true
cleanup = true
no_self_update = false

[brew]
greedy_cask = true
greedy_latest = true
autoremove = true
greedy_auto_updates = true
fetch_head = true
