[v1]
"cargo-bundle 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bundle"]
"cargo-cache 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cache"]
"cargo-update 11.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-watch 8.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"fd-find 8.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"selene 0.23.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["selene"]
"stylua 0.15.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["stylua"]
"trunk 0.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
"twiggy 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["twiggy"]
"wasm-bindgen-cli 0.2.83 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "wasm-bindgen",
    "wasm-bindgen-test-runner",
    "wasm2es6js",
]
"wasm-server-runner 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-server-runner"]
