complete -c bun -f
complete -c bun -n __fish_use_subcommand -a run -d 'Run JavaScript, a package.json script, or a bin'
complete -c bun -n __fish_use_subcommand -a test -d 'Run unit tests'
complete -c bun -n __fish_use_subcommand -a x -d 'Install and execute a package bin (bunx)'
complete -c bun -n __fish_use_subcommand -a repl -d 'Start a REPL session'
complete -c bun -n __fish_use_subcommand -a init -d 'Start an empty project'
complete -c bun -n __fish_use_subcommand -a create -d 'Create a new project (bun c)'
complete -c bun -n __fish_use_subcommand -a install -d 'Install dependencies (bun i)'
complete -c bun -n __fish_use_subcommand -a add -d 'Add a dependency (bun a)'
complete -c bun -n __fish_use_subcommand -a remove -d 'Remove a dependency (bun rm)'
complete -c bun -n __fish_use_subcommand -a update -d 'Update outdated dependencies'
complete -c bun -n __fish_use_subcommand -a outdated -d 'Show latest versions of outdated dependencies'
complete -c bun -n __fish_use_subcommand -a link -d 'Link an npm package globally'
complete -c bun -n __fish_use_subcommand -a unlink -d 'Unlink an npm package'
complete -c bun -n __fish_use_subcommand -a pm -d 'More package management commands'
complete -c bun -n __fish_use_subcommand -a build -d 'Bundle TypeScript & JavaScript'
complete -c bun -n __fish_use_subcommand -a upgrade -d 'Get the latest version of bun'
complete -c bun -n __fish_use_subcommand -a help -d 'Show help'
complete -c bun -n '__fish_seen_subcommand_from run' -a '(bun getcompletes s)' -d 'script'
complete -c bun -n '__fish_seen_subcommand_from run' -a '(bun getcompletes b)' -d 'bin'
complete -c bun -s h -l help -d 'Show help'
complete -c bun -s V -l version -d 'Show version'
