"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$cmd_duration"

add_newline = false

palette = "dark_flat"

[palettes.dark_flat]
green = "#3dd177"
cyan = "#64fcda"
orange = "#ff6633"
aqua = "#00b0ff"

[cmd_duration]
min_time = 1
show_milliseconds = true
format = "[$duration]($style)"
style = "bold cyan"

[character]
success_symbol = "[󰍳 ](green)"
error_symbol = "[ ](orange)"

[directory]
style = "bold aqua"

[git_branch]
always_show_remote = true
style = "green"

[lua]
symbol = " "
